# -*- coding: utf-8 -*-
"""home_page.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SyL-nXT1PFdxi4OYUhzEpXuKZHvD3jA
"""


import pandas as pd
import streamlit as st
import pickle
from PIL import Image
import numpy as np

ada = pickle.load(open('model.pkl', 'rb'))
st.title('Predictor')
mean_int_prof = st.slider('Mean of the integrated profile', 0.0, 200.0, 100.0)
std_int_prof = st.slider('Standard deviation of the integrated profile', 0.0, 100.0, 40.0)
skew_int_prof = st.slider('Skewness of the integrated profile', -2.0, 50.0, 90.0)
std_dmsnr = st.slider('Standard deviation of the DM-SNR curve',0.0,50,120.0)
mean_dmsnr = st.slider('Mean of the DM-SNR curve', 0.0, 140.0, 40.0)
exk_dmsnr = st.slider('Excess kurtosis of the DM-SNR curve', -5.0, 50.0, 30.0)

input_data  = np.array([mean_int_prof,std_int_prof,skew_int_prof,std_dmsnr,mean_dmsnr,exk_dmsnr]).reshape(1,-1)
if st.button('Predict'):
  res = ada.predict(input_data)[0]
  st.subheader('Results')
  st.write(f"Prediction: {'positive' if res == 1 else 'negative'}")

st.subheader('Feature importances: ')
st.image('feature_importance_app.png')
